#!/bin/bash

#SBATCH --partition=unkillable                           # Ask for unkillable job
#SBATCH --cpus-per-task=6                               # Ask for 6 CPUs
#SBATCH --gres=gpu:1                                   # Ask for 1 GPU
#SBATCH --mem=32G                                        # Ask for 10 GB of RAM
#SBATCH --time=20:00:00                                   # The job will run for 3 hours
#SBATCH -o /network/scratch/r/roger.creus-castanyer/slurm-%j.out  # Write the log on scratch


# 1. Load your environment
module load anaconda/3

conda activate /home/mila/r/roger.creus-castanyer/anaconda3/envs/crafter

python3 -u -m src.representations.main.curl_test curl

# 5. Copy whatever you want to save on $SCRATCH
cp -r $SLURM_TMPDIR/tmp/checkpoints/ /network/scratch/r/roger.creus-castanyer/