#!/bin/bash

#SBATCH --partition=main                           # Ask for unkillable job
#SBATCH --cpus-per-task=6                           # Ask for 6 CPUs
#SBATCH --gres=gpu:1                                   # Ask for 1 GPU
#SBATCH --mem=48G                                      # Ask for 10 GB of RAM
#SBATCH --time=35:40:00                                   # The job will run for 3 hours
#SBATCH -o /network/scratch/r/roger.creus-castanyer/slurm-%j.out  # Write the log on scratch

module load anaconda/3

conda activate /home/mila/r/roger.creus-castanyer/anaconda3/envs/crafter

python3 -u -m src.representations.main.generic_vae_train -c vae.yml

# 5. Copy whatever you want to save on $SCRATCH
cp -r $SLURM_TMPDIR/tmp/checkpoints/ /network/scratch/r/roger.creus-castanyer/