model_params:
  name: 'BetaVAE'
  in_channels: 3
  latent_dim: 64
  loss_type: 'B'
  gamma: 10.0
  max_capacity: 25
  Capacity_max_iter: 10000
  use_semantic : False

exp_params:
  batch_size: 2048
  lr: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.0000025
  manual_seed: 1265
  split : 0.9
  trajectories: ['observations/env_3125','observations/env_3126','observations/env_3127','observations/env_3128','observations/env_3129','observations/env_3130','observations/env_3131','observations/env_3132','observations/env_3133','observations/env_3134']
  #trajectories: ['observations/env_2022', 'observations/env_2023', 'observations/env_2024']

trainer_params:
  max_epochs: 100
