experiment: 'crafter_curl'
environment: 'CrafterReward-v1'
#trajectories: ['observations/env_2022','observations/env_2023','observations/env_2024','observations/env_2025','observations/env_2026','observations/env_2027','observations/env_2028','observations/env_2029','observations/env_2030','observations/env_2031']
trajectories: ['observations/env_2022'] # THIS HAS TO BE INDIVIDUAL FOR CONSTRUCT MAP, ALL FOR COMPUTE EMBEDDINGS
epochs: 30
batch_size: 128
lr: 0.001
split: 0.90
tau: 0.005
soft_update: 2
img_size: 64
delay: yes

curl:
  k_std: 5
  k_mean: 15
  z_dim: 256
  #trajectories: ['observations/env_2022','observations/env_2023','observations/env_2024','observations/env_2025','observations/env_2026','observations/env_2027','observations/env_2028','observations/env_2029','observations/env_2030','observations/env_2031']
  load_clusters: True # THIS HAS TO BE FALSE DURING TRAINING AND TRUE TO GENERATE THE MAPS
  path_clusters: '/home/mila/r/roger.creus-castanyer/modded-crafter/src/representations/clusters/curl'
test:
  type: 'index'
  shuffle: no
  limit: 50000 # this is not used
  load_clusters: True
  path_weights: 'epoch=29-step=253410.ckpt'
  