experiment: 'crafter_curl'
environment: 'CrafterReward-v1'
trajectories: ['observations/env_125']
epochs: 100
batch_size: 32
lr: 0.001
split: 0.90
tau: 0.005
soft_update: 2
img_size: 64
delay: yes

curl:
  k_std: 5
  k_mean: 15
  z_dim: 512
  trajectories: ['env_125']
  load_clusters: True # THIS HAS TO BE FALSE DURING TRAINING AND TRUE TO GENERATE THE MAPS
  path_clusters: '/home/roger/Desktop/modded-crafter/src/representations/trajectories/clusters/curl'
test:
  type: 'index'
  shuffle: no
  limit: 50000 # this is not used
  load_clusters: True
  path_weights: 'epoch=99-step=210100.ckpt'
  