model_params:
  name: 'SemanticPredictorExperiment'
  in_channels: 3
  latent_dim: 256
  loss_type: 'B'
  gamma: 10.0
  max_capacity: 25
  Capacity_max_iter: 10000
  use_semantic : False

exp_params:
  batch_size: 256
  lr: 0.005
  weight_decay: 0.0
  weights : "/home/mila/r/roger.creus-castanyer/modded-crafter/crafter/11yjamlv/checkpoints/epoch=99-step=413300.ckpt"
  scheduler_gamma: 0.95
  manual_seed: 1265
  split : 0.9
  trajectories: ['observations/env_3125','observations/env_3126','observations/env_3127','observations/env_3128','observations/env_3129','observations/env_3130','observations/env_3131','observations/env_3132','observations/env_3133','observations/env_3134']

trainer_params:
  max_epochs: 30