model_params:
  name: 'SeqVAE'
  in_channels: 3
  num_actions: 17
  latent_dim: 256
  z1_dim: 32
  z2_dim: 256
  hidden_units: 256

exp_params:
  batch_size: 64
  kl_weight: 0.00025
  lr: 0.0001
  weight_decay: 0.0
  manual_seed: 1265
  split : 0.9
  trajectories: ['observations/env_1234','observations/env_1235','observations/env_1236','observations/env_1237','observations/env_1238','observations/env_1239','observations/env_1240', 'observations/env_1241', 'observations/env_1242', 'observations/env_1243']

trainer_params:
  max_epochs: 300
